
name: mesheryctl-smp

on:
  [push, repository_dispatch]
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  

jobs:
  perftest:
    runs-on: ubuntu-latest
    steps:
     # - uses: actions/checkout@v2
     # /bin/bash -c "curl -LO 'https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl'"
      #    /bin/bash -c "curl -L https://git.io/meshery | PLATFORM=kubernetes  bash -"
      - name: install go
        run: sudo apt install golang
      
      - name: Install mesheryctl
        run: |
         git clone https://github.com/layer5io/meshery.git; cd meshery/mesheryctl
         make
         sudo mv ./mesheryctl /usr/local/bin/
                    
      - name: export token    
        run: export TOKEN="${{ secrets.AUTH_TOKEN }}"

      - name: pipe to file
        run: |
          echo '{ "meshery-provider": "Meshery", "token": null }' | jq '.token = env.TOKEN' > ~/auth.json

      - name: setup minikube
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'

      - name: deploy meshery
        run: |
          export PLATFORM=kubernetes
          mesheryctl system start --yes
         


      - name:  configure meshery
        run: |
          kubectl config view --minify --flatten > ~/minified_config
          mv ~/minified_config ~/.kube/config


      - name: perfom smi conformance tests
        run: mesheryctl perf --name "mesheryctl action perf tests" --url https://www.google.com --qps 4 --concurrent-requests 1 --duration 6s --token ~/auth.json
  
